//
//  HelpConstant.h
//  retailapp
//
//  Created by guozhi on 2017/3/8.
//  Copyright © 2017年 杭州迪火科技有限公司. All rights reserved.
//

#ifndef HelpConstant_h
#define HelpConstant_h
//这里面的值和help.plist里面的key要一一对应
//----------------员工管理--------------
//角色权限
#define HELP_EMPLOYEE_ROLE_PERMISSION @"HELP_EMPLOYEE_ROLE_PERMISSION"
//员工信息
#define HELP_EMPLOYEE_INFORMATION @"HELP_EMPLOYEE_INFORMATION"
//员工详情信息
#define HELP_EMPLOYEE_INFORMATION_DETAIL @"HELP_EMPLOYEE_INFORMATION_DETAIL"
//角色提成设置
#define HELP_EMPLOYE_ROLE_SETTING @"HELP_EMPLOYE_ROLE_SETTING"
//导购员业绩目标
#define HELP_EMPLOYE_SHOPPING_GUIDE @"HELP_EMPLOYE_SHOPPING_GUIDE"
//主页显示设置
#define HELP_EMPLOYE_MAIN_PAGE_SHOW_SETTING @"HELP_EMPLOYE_MAIN_PAGE_SHOW_SETTING"

//----------------营业设置--------------
//店家信息
#define HELP_SETTING_SHOP_INFO @"HELP_SETTING_SHOP_INFO"
//系统参数
#define HELP_SETTING_SYSTEM_PARAMETER @"HELP_SETTING_SYSTEM_PARAMETER"
//支付方式
#define HELP_SETTING_PAYMENT_METHOD @"HELP_SETTING_PAYMENT_METHOD"
//小票设置
#define HELP_SETTING_SMALL_TICKET_SET @"HELP_SETTING_SMALL_TICKET_SET"
//客单备注
#define HELP_SETTING_GUEST_MEMO @"HELP_SETTING_GUEST_MEMO"
//短信设置
#define HELP_SETTING_SMS_SETTEING @"HELP_SETTING_SMS_SETTEING"
//数据清理
#define HELP_SETTING_DATA_CLEAR @"HELP_SETTING_DATA_CLEAR"

//----------------营销管理--------------
//特价管理主页
#define HELP_MARKET_SPECIAL_MANAGEMENT_LIST @"HELP_MARKET_SPECIAL_MANAGEMENT_LIST"
//特价管理详情页
#define HELP_MARKET_SPECIAL_MANAGEMENT_DETAIL @"HELP_MARKET_SPECIAL_MANAGEMENT_DETAIL"
//特价管理活动详情页
#define HELP_MARKET_SPECIAL_MANAGEMENT_ACTIVITY_DETAIL @"HELP_MARKET_SPECIAL_MANAGEMENT_ACTIVITY_DETAIL"

//满送/换购主页
#define HELP_MARKET_FULL_DELIVERY_LIST @"HELP_MARKET_FULL_DELIVERY_LIST"
//满送/换购详情页
#define HELP_MARKET_FULL_DELIVERY_DETAIL @"HELP_MARKET_FULL_DELIVERY_DETAIL"
//满送/换购活动详情页
#define HELP_MARKET_FULL_DELIVERY_ACTIVITY_DETAIL @"HELP_MARKET_FULL_DELIVERY_ACTIVITY_DETAIL"

//满减主页
#define HELP_MARKET_FULL_CUT_LIST @"HELP_MARKET_FULL_CUT_LIST"
//满减详情页
#define HELP_MARKET_FULL_CUT_DETAIL @"HELP_MARKET_FULL_CUT_DETAIL"
//满减活动详情页
#define HELP_MARKET_FULL_CUT_ACTIVITY_DETAIL @"HELP_MARKET_FULL_CUT_ACTIVITY_DETAIL"

//捆绑打折主页
#define HELP_MARKET_BUNDLED_DISCOUNT_LIST @"HELP_MARKET_BUNDLED_DISCOUNT_LIST"
//捆绑打折详情页
#define HELP_MARKET_BUNDLED_DISCOUNT_DETAIL @"HELP_MARKET_BUNDLED_DISCOUNT_DETAIL"
//捆绑打折活动详情页
#define HELP_MARKET_BUNDLED_DISCOUNT_ACTIVITY_DETAIL @"HELP_MARKET_BUNDLED_DISCOUNT_ACTIVITY_DETAIL"

//第N件打折主页
#define HELP_MARKET_PART_N_DISCOUNT_LIST @"HELP_MARKET_PART_N_DISCOUNT_LIST"
//第N件打折详情页
#define HELP_MARKET_PART_N_DISCOUNT_DETAIL @"HELP_MARKET_PART_N_DISCOUNT_DETAIL"
//第N件打折活动详情页
#define HELP_MARKET_PART_N_DISCOUNT_ACTIVITY_DETAIL @"HELP_MARKET_PART_N_DISCOUNT_ACTIVITY_DETAIL"

//优惠券主页
#define HELP_MARKET_COUPON_LIST @"HELP_MARKET_COUPON_LIST"
//优惠券详情页
#define HELP_MARKET_COUPON_DETAIL @"HELP_MARKET_COUPON_DETAIL"
//优惠券活动详情页
#define HELP_MARKET_COUPON_ACTIVITY_DETAIL @"HELP_MARKET_COUPON_ACTIVITY_DETAIL"


//生日促销
#define HELP_MARKET_BIRTHDAY_PROMOTION @"HELP_MARKET_BIRTHDAY_PROMOTION"

//----------------微店管理--------------
//配送管理
#define HELP_WECHAT_DISTRIBUTION_MANAGEMENT @"HELP_WECHAT_DISTRIBUTION_MANAGEMENT"
//销售订单订单列表页
#define HELP_WECHAT_SALE_ORDER_LIST @"HELP_WECHAT_SALE_ORDER_LIST"
//销售订单订单详情页
#define HELP_WECHAT_SALE_ORDER_DETAIL @"HELP_WECHAT_SALE_ORDER_DETAIL"
//销售订单配送信息页
#define HELP_WECHAT_SALE_ORDER_SEND_INFO @"HELP_WECHAT_SALE_ORDER_SEND_INFO"
//销售订单拒绝原因页
#define HELP_WECHAT_SALE_ORDER_REFUSE_REASON @"HELP_WECHAT_SALE_ORDER_REFUSE_REASON"
//积分兑换订单列表页
#define HELP_WECHAT_INTERGAL_EXCHANGE_ORDER_LIST @"HELP_WECHAT_INTERGAL_EXCHANGE_ORDER_LIST"
//积分兑换订单详情页
#define HELP_WECHAT_INTERGAL_EXCHANGE_ORDER_DETAIL @"HELP_WECHAT_INTERGAL_EXCHANGE_ORDER_DETAIL"
//退货审核列表页
#define HELP_WECHAT_RETURN_AUDIT_LIST @"HELP_WECHAT_RETURN_AUDIT_LIST"
//退货审核详情页
#define HELP_WECHAT_RETURN_AUDIT_DETAIL @"HELP_WECHAT_RETURN_AUDIT_DETAIL"
//退款管理
#define HELP_WECHAT_REFUND_MANAGEMENT @"HELP_WECHAT_REFUND_MANAGEMENT"
//微店主页设置
#define HELP_WECHAT_HOME_SETTING @"HELP_WECHAT_HOME_SETTING"
//微店商品信息
#define HELP_WECHAT_GOODS_INFO @"HELP_WECHAT_GOODS_INFO"
//微店商品详情
#define HELP_WECHAT_GOODS_INFO_DETAIL @"HELP_WECHAT_GOODS_INFO_DETAIL"
//微店可销售数量设置
#define HELP_WECHAT_SALE_COUNT @"HELP_WECHAT_SALE_COUNT"

//----------------商品管理--------------
//商品分类列表页
#define HELP_GOODS_CATEGORY_LIST @"HELP_GOODS_CATEGORY_LIST"
//商品分类详情页
#define HELP_GOODS_CATEGORY_DETAIL @"HELP_GOODS_CATEGORY_DETAIL"
//商品信息列表页
#define HELP_GOODS_INFO_LIST @"HELP_GOODS_INFO_LIST"
//商品详情
#define HELP_GOODS_DETAIL @"HELP_GOODS_DETAIL"
//商品拆分
#define HELP_GOODS_SPLIT @"HELP_GOODS_SPLIT"
//商品组装
#define HELP_GOODS_ASSEMBLE @"HELP_GOODS_ASSEMBLE"
//商品加工
#define HELP_GOODS_MACHINING @"HELP_GOODS_MACHINING"

//----------------库存管理--------------
//库存查询
#define HELP_STOCK_QUERY @"HELP_STOCK_QUERY"
//库存调整
#define HELP_STOCK_ADJUST @"HELP_STOCK_ADJUST"
//库存盘点
#define HELP_STICK_CHECK @"HELP_STICK_CHECK"
//盘点记录
#define HELP_STOCK_CHECK_RECORD @"HELP_STOCK_CHECK_RECORD"
//提醒设置
#define HELP_STOCK_ALERT_SETTING @"HELP_STOCK_ALERT_SETTING"

//----------------会员管理--------------
//会员主页
#define HELP_MEMBER_HOEMPAGE @"HELP_MEMBER_HOEMPAGE"
//会员卡类型
#define HELP_MEMBER_CARD_TYPE @"HELP_MEMBER_CARD_TYPE"
//积分兑换设置
#define HELP_MEMBER_INTEGRAL_EXCHANGE_SETTING @"HELP_MEMBER_INTEGRAL_EXCHANGE_SETTING"
//充值优惠促销
#define HELP_MEMBER_RECHARGE_PROMOTIONS @"HELP_MEMBER_RECHARGE_PROMOTIONS"
//发会员卡
#define HELP_MEMBER_SEND_MEMBER_CARD @"HELP_MEMBER_SEND_MEMBER_CARD"
//会员换卡
#define HELP_MEMBER_MEMBER_CHANGE_CARD @"HELP_MEMBER_MEMBER_CHANGE_CARD"
//会员赠分
#define HELP_MEMBER_MEMBER_SEND_INTERGAL @"HELP_MEMBER_MEMBER_SEND_INTERGAL"
//改卡密码
#define HELP_MEMBER_MEMBER_CHANGE_PASSWORD @"HELP_MEMBER_MEMBER_CHANGE_PASSWORD"
//会员充值
#define HELP_MEMBER_RECHARGE @"HELP_MEMBER_RECHARGE"
//积分兑换
#define HELP_MEMBER_INTERGAL_EXCHANGE @"HELP_MEMBER_INTERGAL_EXCHANGE"
//会员退卡
#define HELP_MEMBER_RETUEN_CARD @"HELP_MEMBER_RETUEN_CARD"
//会员卡挂失
#define HELP_MEMBER_CARD_LOSS @"HELP_MEMBER_CARD_LOSS"
//短信营销
#define HELP_MEMBER_SMS_MARKET @"HELP_MEMBER_SMS_MARKET"
//生日提醒
#define HELP_MEMBER_BIRTHDAY_ALERTING @"HELP_MEMBER_BIRTHDAY_ALERTING"

//----------------出入库管理--------------
//收货入库单
#define HELP_OUTIN_RECEIVING_ORDER @"HELP_OUTIN_RECEIVING_ORDER"
//退货出库单
#define HELP_OUTIN_RETURN_ORDER @"HELP_OUTIN_RETURN_ORDER"
//出入库记录
#define HELP_OUTIN_RECORD @"HELP_OUTIN_RECORD"
//供应商
#define HELP_OUTIN_SUPPLIER @"HELP_OUTIN_SUPPLIER"

//----------------电子收款账户--------------
//电子收款账户
#define HELP_PAYMENT_ACCOUNT @"HELP_PAYMENT_ACCOUNT"

//----------------顾客评价--------------
//顾客评价
#define HELP_COMMENT @"HELP_COMMENT"



#endif /* HelpConstant_h */
