//
//  Header.h
//  retailapp
//
//  Created by zhangzhiliang on 15/7/7.
//  Copyright (c) 2015年 杭州迪火科技有限公司. All rights reserved.
//

#ifndef retailapp_Header_h
#define retailapp_Header_h

//会员类型编辑页面
#define MEMBER_TYPE_EDIT_ISUPGRADE 1
#define MEMBER_TYPE_EDIT_NEXTCARDTYPE 2
#define MEMBER_TYPE_EDIT_PRICESCHEME 3
#define MEMBER_TYPE_EDIT_NEEDINTEGRAL 28
#define MEMBER_TYPE_EDIT_INTEGRALRATIO 29
#define MEMBER_TYPE_EDIT_DISCOUNTRATIO 30


//会员充值促销编辑页面
#define MEMBER_RECHARGE_SALES_EDIT_STARTTIME 4
#define MEMBER_RECHARGE_SALES_EDIT_ENDTIME 5
#define MEMBER_RECHARGE_SALES_EDIT_RECHARGETHRESHOLD 32
#define MEMBER_RECHARGE_SALES_EDIT_MONEY 33
#define MEMBER_RECHARGE_SALES_EDIT_POINT 34

//会员信息编辑页面
#define MEMBER_INFO_EDIT_RECHARGE_BUTTON 6
#define MEMBER_INFO_EDIT_DEAL_RECORD_SEARCH_BUTTON 7
#define MEMBER_INFO_EDIT_EXCHANGE_GOODS_BUTTON 8
#define MEMBER_INFO_EDIT_SEX 22
#define MEMBER_INFO_EDIT_KINSCARDNAME 23
#define MEMBER_INFO_EDIT_STATUS 24
#define MEMBER_INFO_EDIT_ISPWD 25
#define MEMBER_INFO_EDIT_BIRTHDAY 26
#define MEMBER_INFO_EDIT_ZIPCODE 27
#define MEMBER_INFO_EDIT_PWD 39

//会员筛选页面
#define MEMBER_TOP_SELECT_KIND_CARD_NAME 9
#define MEMBER_TOP_SELECT_STATUS 10
#define MEMBER_TOP_SELECT_DISPOSE_NAME 11
#define MEMBER_TOP_SELECT_ACTIVE_TIME 12
#define MEMBER_TOP_SELECT_START_TIME 13
#define MEMBER_TOP_SELECT_END_TIME 14
#define MEMBER_TOP_SELECT_ACTIVE_WAY 15
#define MEMBER_TOP_SELECT_ACTIVE_SHOP 16
#define MEMBER_TOP_SELECT_MEMBER_BIR 17

//会员信息页面
#define MEMBER_INFO_LIST_MYMEMBER 18
#define MEMBER_INFO_LIST_MEMBERSUM 19
#define MEMBER_INFO_LIST_CURRENTMONTHMEMBERSUM 20

//充值记录刷选
#define CHARGE_RECORD_SELECT_TOP_DATE 21

//充值记录刷选
#define CARD_CANCEL_EDIT_AMOUNT 31

//会员充值编辑页面
#define MEMBER_RECHARGE_EDIT_RECHARGEKIND 35
#define MEMBER_RECHARGE_EDIT_PAYMODE 36
#define MEMBER_RECHARGE_EDIT_RECHARGEMONEY 37

//会员积分兑换设置编辑
#define DEGREE_GOODS_EDIT_NEEDPOINT 38

#endif
