//
//  GoodsModuleEvent.h
//  retailapp
//
//  Created by zhangzhiliang on 15/7/27.
//  Copyright (c) 2015年 杭州迪火科技有限公司. All rights reserved.
//

#ifndef retailapp_GoodsModuleEvent_h
#define retailapp_GoodsModuleEvent_h

//商品分类编辑页面
#define GOODS_CATEGORY_EDIT_ISHASPARENT 1
#define GOODS_CATEGORY_EDIT_PARENTNAME 2

//商品批量销售设置
#define GOODS_BATCH_SALE_SETTING_RATIO 3

//商品编辑页面设置
#define GOODS_EDIT_UPDOWNSTATUS 6
#define GOODS_EDIT_MICROINFO 7
#define GOODS_EDIT_SYNSHOP 46
#define GOODS_EDIT_BRAND 47
#define GOODS_EDIT_CATEGORY 48
#define GOODS_EDIT_PURPRICE 49
#define GOODS_EDIT_RETAILPRICE 50
#define GOODS_EDIT_MEMBERPRICE 51
#define GOODS_EDIT_WHOPRICE 52
#define GOODS_EDIT_RATIO 53
#define GOODS_EDIT_PERIOD 74
#define GOODS_EDIT_INBULKGOODS 79
#define GOODS_EDIT_NOWSTORE 100
#define GOODS_EDIT_UTIT 101
#define GOODS_EDIT_RAWUNITPRINCE 102

//微店商品编辑页面设置
#define GOODS_MICRO_EDIT_ISSALE 8
#define GOODS_MICRO_EDIT_ISUPDOWNSTATUS 9
#define GOODS_MICRO_EDIT_PICTUREINFO 10
#define GOODS_MICRO_EDIT_SALESSTRATEGY 11
#define GOODS_MICRO_EDIT_PRIORITY 55
#define GOODS_MICRO_EDIT_DISCOUNT 56
#define GOODS_MICRO_EDIT_WEIXINPRICE 57

//商品款式筛选页面设置
#define GOODS_STYLE_TOP_SELECT_GOODSCATEGORY 11
#define GOODS_STYLE_TOP_SELECT_YEAR 12
#define GOODS_STYLE_TOP_SELECT_SEASON 13
#define GOODS_STYLE_TOP_SELECT_SHOP 14

//商品款式编辑页面
#define GOODS_STYLE_EDIT_GOODS_EVENT @"GOODS_STYLE_EDIT_GOODS_EVENT" //商品信息

#define GOODS_STYLE_EDIT_UPDOWNSTATUS 14 // 款式上下架
#define GOODS_STYLE_EDIT_PURPRICE 15 // 进货价
#define GOODS_STYLE_EDIT_RETAILPRICE 16 // 零售价
#define GOODS_STYLE_EDIT_MEMBERPRICE 17 // 会员价
#define GOODS_STYLE_EDIT_WHOPRICE 18 // 批发价
#define GOODS_STYLE_EDIT_STYLEINFOSYN 19 // 款式信息同步
#define GOODS_STYLE_EDIT_CATEGORY 20 // 分类
#define GOODS_STYLE_EDIT_BRAND 21 // 品牌
#define GOODS_STYLE_EDIT_SEX 22 // 适用性别
#define GOODS_STYLE_EDIT_SERIES 23 // 系列
#define GOODS_STYLE_EDIT_YEAR 24 // 年度
#define GOODS_STYLE_EDIT_SEASON 25 // 季节
#define GOODS_STYLE_EDIT_PHASE 26 // 阶段
#define GOODS_STYLE_EDIT_FABRIC 27 // 面料
#define GOODS_STYLE_EDIT_MATERIAL 28 // 里料
#define GOODS_STYLE_EDIT_SALEROYALTYRATIO 29 // 销售提成比例
#define GOODS_STYLE_EDIT_MICROINFO 30  // 微店信息
#define GOODS_STYLE_EDIT_HANGTAGPRICE 32 // 吊牌价
#define GOODS_STYLE_EDIT_GOODSINFO 68 // 添加、编辑商品信息
#define GOODS_STYLE_EDIT_MAINMODEL 75 // 主型
#define GOODS_STYLE_EDIT_AUXILIARYMODEL 76 // 辅型
#define GOODS_STYLE_EDIT_UNIT 77 //单位

//商品款式商品详情页面
#define GOODS_STYLE_GOODS_EDIT_PURPRICE 33 // 进货价
#define GOODS_STYLE_GOODS_EDIT_RETAILPRICE 35 // 零售价
#define GOODS_STYLE_GOODS_EDIT_MEMBERPRICE 36 // 会员价
#define GOODS_STYLE_GOODS_EDIT_WHOPRICE 37 // 批发价

//商品款式微店详情
#define GOODS_STYLE_MICRO_EDIT_GOODS_EVENT @"GOODS_STYLE_MICRO_EDIT_GOODS_EVENT" //商品款式微店信息

//商品店内码规则设置页面
#define GOODS_INNERCODE_REGULATION_SETTING_ISUSED 38 // 是否启用自定义规则设置店内码

//商品销售包管理一览筛选页面
#define GOODS_SALE_PACK_TOP_SELECT_DATE 39 // 日期

//商品销售包管理编辑页面
#define GOODS_SALE_PACK_MANAGE_EDIT_STARTTIME 40 // 适用开始时间
#define GOODS_SALE_PACK_MANAGE_EDIT_ENDTIME 41 // 适用结束时间
#define GOODS_SALE_PACK_MANAGE_EDIT_ORGANIZATIONNAME 42 // 适用机构


//商品属性值编辑页面
#define GOODS_SINGLE_ATTRIBUTE_EDIT_CATEGORY 43 // 属性值分类

//商品信息主页面
#define GOODS_INFO_SELECT_SHOPNAME 44 // 门店

//微店关联价格编辑
#define MICRO_PRICE_MINDISCOUNT 58
#define MICRO_PRICE_MAXDISCOUNT 59

//款式主页
#define GOODS_STYLE_INFO_SHOPNAME 60 // 门店

//款式一览
#define GOODS_STYLE_LIST_SHOPNAME 61 // 门店

//款式帅选
#define STYLE_TOP_SELECT_CATEGORY 62 // 分来
#define STYLE_TOP_SELECT_SEX 63 //  性别
#define STYLE_TOP_SELECT_YEAR 64 // 年度
#define STYLE_TOP_SELECT_SEASON 65 //   季节
#define STYLE_TOP_SELECT_MINPRICE 66 // 最低吊牌价
#define STYLE_TOP_SELECT_MAXPRICE 67 // 最高吊牌价
#define STYLE_TOP_SELECT_MAINMODEL 77 // 主型
#define STYLE_TOP_SELECT_AUXILIARYMODEL 78 // 辅型

//款式商品价格设置
#define STYLE_GOODS_PRICE_PURPRICE 69 // 进货价
#define STYLE_GOODS_PRICE_RETAILPRICE 70 // 零售价
#define STYLE_GOODS_PRICE_MEMBERPRICE 71 // 会员价
#define STYLE_GOODS_PRICE_WHOPRICE 72 // 批发价
#define STYLE_GOODS_PRICE_HANGTAGPRICE 73 // 吊牌价

#endif
